import './admin-env';
import { before, after, it } from 'node:test';
import assert from 'node:assert/strict';
import type { AddressInfo } from 'node:net';
import { randomUUID } from 'node:crypto';
import { buildApp } from '../src/app';
import { query, queryOne } from '../src/db/psql';
import { buildTestPng } from './fixtures';
import { permissions } from '../src/modules/admin/policy';
const server = buildApp();
let base: string;
before(async () => { await new Promise<void>(r => server.listen(0, r)); base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; });
after(async () => { await new Promise<void>(r => server.close(() => r())); });
async function request(path: string, method = 'GET', data?: unknown, headers: Record<string, string> = {}) { const r = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...headers }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) }); return { status: r.status, body: r.status === 204 ? null : await r.json() as any, cookie: r.headers.get('set-cookie')?.split(';')[0] ?? '' }; }
async function account(role?: 'ADMIN' | 'SUPER_ADMIN', granted: readonly string[] = permissions, password = 'correcthorsebattery') { const tag = randomUUID().slice(0, 8); const input = { email: `ad_${tag}@example.com`, username: `ad_${tag}`, password, displayName: 'Test operator' }; const r = await request('/api/v1/auth/signup', 'POST', input); assert.equal(r.status, 201); const id = r.body.user.id as string; const token = r.body.tokens.accessToken as string; if (role)
    await query(`INSERT INTO admin_grants(user_id,role,permissions) VALUES(:'id',:'role',:'permissions'::jsonb)`, { id, role, permissions: JSON.stringify(granted) }); return { id, token, input }; }
async function login(a: Awaited<ReturnType<typeof account>>) { const r = await request('/api/v1/admin/login', 'POST', { email: a.input.email, password: a.input.password }, { Origin: 'http://admin.test' }); assert.equal(r.status, 200, JSON.stringify(r.body)); assert.match(r.cookie, /katkee_admin=/); return { Cookie: r.cookie, Origin: 'http://admin.test', 'X-CSRF-Token': r.body.csrf as string }; }
async function photo(a: Awaited<ReturnType<typeof account>>) { const r = await fetch(base + '/api/v1/media/photos', { method: 'POST', headers: { Authorization: `Bearer ${a.token}`, 'Content-Type': 'image/png' }, body: buildTestPng(4, 4) }); assert.equal(r.status, 201); return ((await r.json()) as any).media.id as string; }
it('lets suspended users appeal only their own notices using expiring, single-use access',async()=>{
    const owner=await account(),other=await account(),admin=await account('SUPER_ADMIN');
    const mediaId=await photo(owner);
    const story=await request('/api/v1/stories','POST',{mediaId,caption:'Visibility test'},{Authorization:`Bearer ${owner.token}`});
    const action=await queryOne(`WITH a AS(INSERT INTO moderation_actions(actor_id,target_type,target_id,action,reason,previous_state,new_state) VALUES(:'actor','user',:'user','suspend','Test review','{}','{}') RETURNING id),n AS(INSERT INTO moderation_notices(user_id,action_id) SELECT :'user',id FROM a) SELECT id FROM a`,{actor:admin.id,user:owner.id});
    await query(`UPDATE users SET is_active=false,moderation_state='SUSPENDED' WHERE id=:'id'`,{id:owner.id});
    const viewerHeaders={Authorization:`Bearer ${other.token}`};
    for(const path of [`/api/v1/stories/${story.body.story.id}`,`/api/v1/media/${mediaId}/file`,`/api/v1/users/${owner.input.username}`,`/api/v1/users/${owner.input.username}/stories`,`/api/v1/users/${owner.input.username}/highlights`]){
      const denied=await fetch(base+path,{headers:viewerHeaders});assert.equal(denied.status,404,path);await denied.text();
    }
    const search=await request('/api/v1/search/users?q='+owner.input.username,'GET',undefined,viewerHeaders);assert.deepEqual(search.body.results,[]);
    const access=await request('/api/v1/moderation/access','POST',owner.input);
    assert.equal(access.status,200);assert.equal(access.body.items[0].actionId,action!.id);
    const stranger=await request('/api/v1/moderation/access','POST',other.input);
    assert.deepEqual(stranger.body.items,[]);
    const send=(ticket:string)=>request('/api/v1/moderation/appeal/submit','POST',{ticket,actionId:action!.id,reason:'Please review my account.'});
    assert.equal((await send(stranger.body.ticket)).status,401);
    assert.equal((await send(access.body.ticket)).status,200);
    assert.equal((await send(access.body.ticket)).status,401);
    const status=await queryOne(`SELECT is_active FROM users WHERE id=:'id'`,{id:owner.id});assert.equal(status!.is_active,'f');
    const again=await request('/api/v1/moderation/access','POST',owner.input);assert.equal(again.body.items[0].appealStatus,'OPEN');
});
it('rejects USER, missing sessions, CSRF violations and self-escalation; grants are live', async () => {
    const user = await account();
    const admin = await account('ADMIN', ['reports.read'], ' correct horse battery ');
    const superAdmin = await account('SUPER_ADMIN');
    assert.equal((await request('/api/v1/admin/reports', 'GET', undefined, { Authorization: `Bearer ${user.token}` })).status, 401);
    assert.equal((await request('/api/v1/admin/login', 'POST', user.input, { Origin: 'http://admin.test' })).status, 403);
    const ah = await login(admin), sh = await login(superAdmin);
    assert.equal((await request('/api/v1/admin/admins', 'GET', undefined, ah)).status, 403);
    assert.equal((await request('/api/v1/admin/moderate', 'POST', { confirmed: true }, { ...sh, 'X-CSRF-Token': 'wrong' })).status, 403);
    assert.equal((await request('/api/v1/admin/admins', 'POST', { userId: admin.id, permissions: ['admins.create'], confirmed: true, version: 1 }, ah)).status, 403);
    assert.equal((await request('/api/v1/admin/admins', 'POST', { userId: superAdmin.id, permissions: [], confirmed: true, version: 1 }, sh)).status, 403);
    assert.equal((await request('/api/v1/admin/admins', 'POST', { userId: user.id, role: 'SUPER_ADMIN', permissions: [], confirmed: true }, sh)).status, 403);
    const added = await request('/api/v1/admin/admins', 'POST', { userId: user.id, role: 'ADMIN', permissions: ['reports.read'], confirmed: true, version: 0 }, sh);
    assert.equal(added.status, 200, JSON.stringify(added.body));
    const uh = await login(user);
    assert.equal((await request('/api/v1/admin/reports', 'GET', undefined, uh)).status, 200);
    const disabled = await request('/api/v1/admin/admins', 'POST', { userId: user.id, permissions: [], enabled: false, confirmed: true, version: 1 }, sh);
    assert.equal(disabled.status, 200);
    assert.equal((await request('/api/v1/admin/reports', 'GET', undefined, uh)).status, 401);
    await assert.rejects(query('UPDATE admin_audit SET action=action WHERE false'));
 assert.equal((await request('/api/v1/admin/reauthenticate', 'POST', {password:admin.input.password}, ah)).status, 204);
 assert.equal((await request('/api/v1/moderation/notices', 'POST', admin.input)).status, 200);
});
it('moderation is atomic, concurrent-safe, hides direct media, and allows explicit restoration and appeals', async () => {
    const owner = await account(), reporter = await account(), admin = await account('ADMIN');
    const ah = await login(admin);
    const mediaId = await photo(owner);
    const published = await request('/api/v1/stories', 'POST', { mediaId, caption: 'Test', audience: 'public', allowComments: 'everyone', allowSharing: true }, { Authorization: `Bearer ${owner.token}` });
    assert.equal(published.status, 201);
    const storyId = published.body.story.id;
    const reported = await request('/api/v1/reports', 'POST', { targetType: 'story', targetId: storyId, reason: 'spam' }, { Authorization: `Bearer ${reporter.token}` });
    assert.equal(reported.status, 201);
    const input = { reportId: reported.body.report.id, version: 1, action: 'remove', reason: 'Test moderation', confirmed: true };
    const results = await Promise.all([request('/api/v1/admin/moderate', 'POST', input, ah), request('/api/v1/admin/moderate', 'POST', input, ah)]);
    assert.deepEqual(results.map(r => r.status).sort(), [200, 409]);
    const direct = await fetch(base + `/api/v1/media/${mediaId}/file`, { headers: { Authorization: `Bearer ${owner.token}` } });
    assert.equal(direct.status, 404);
    assert.equal((await request(`/api/v1/stories/${storyId}`, 'GET', undefined, { Authorization: `Bearer ${reporter.token}` })).status, 404);
    assert.equal((await fetch(base + `/api/v1/admin/evidence/${reported.body.report.id}`)).status, 401);
    assert.equal((await fetch(base + `/api/v1/admin/evidence/${reported.body.report.id}`, { headers: ah })).status, 200);
    const notices = await request('/api/v1/moderation/notices', 'POST', owner.input);
    assert.equal(notices.status, 200);
    assert.ok(notices.body.items.length);
    const appeal = await request('/api/v1/moderation/appeal', 'POST', { ...owner.input, actionId: notices.body.items[0].actionId, reason: 'Please review' });
    assert.equal(appeal.status, 200);
    assert.equal((await request(`/api/v1/stories/${storyId}`, 'GET', undefined, { Authorization: `Bearer ${reporter.token}` })).status, 404);
    const restored = await request('/api/v1/admin/moderate', 'POST', { targetType: 'story', targetId: storyId, action: 'restore', reason: 'Appeal reviewed', confirmed: true }, ah);
    assert.equal(restored.status, 200, JSON.stringify(restored.body));
    assert.equal((await request(`/api/v1/stories/${storyId}`, 'GET', undefined, { Authorization: `Bearer ${reporter.token}` })).status, 200);
    await request('/api/v1/admin/moderate', 'POST', { targetType: 'user', targetId: owner.id, action: 'restrict', reason: 'Test restriction', confirmed: true }, ah);
    assert.equal((await request('/api/v1/stories', 'POST', { mediaId: await photo(owner) }, { Authorization: `Bearer ${owner.token}` })).status, 403);
    await request('/api/v1/admin/moderate', 'POST', { targetType: 'user', targetId: owner.id, action: 'suspend', reason: 'Test suspension', confirmed: true }, ah);
    assert.equal((await request('/api/v1/auth/me', 'GET', undefined, { Authorization: `Bearer ${owner.token}` })).status, 403);
});
it('ads require independent approval, enforce caps/ownership/hide and create real reports/events', async () => {
    const creator = await account('ADMIN'), reviewer = await account('ADMIN'), viewer = await account(), stranger = await account();
    const ch = await login(creator), rh = await login(reviewer);
    const advertiser = await request('/api/v1/admin/advertisers', 'POST', { name: 'Test advertiser', userId: creator.id, confirmed: true }, ch);
    assert.equal(advertiser.status, 201);
    const campaign = await request('/api/v1/admin/campaigns', 'POST', { advertiserId: advertiser.body.id, mediaId: await photo(creator), name: 'Test campaign', startAt: new Date(Date.now() - 60000).toISOString(), endAt: new Date(Date.now() + 3600000).toISOString(), budgetMinor: 0, currency: 'INR', impressionLimit: 10, userCap: 1, dailyCap: 1, caption: 'Sponsored test', cta: 'Learn More', destination: 'https://example.com/', confirmed: true }, ch);
    assert.equal(campaign.status, 201, JSON.stringify(campaign.body));
    const id = campaign.body.id;
    const header = { Authorization: `Bearer ${viewer.token}` };
    assert.equal((await request('/api/v1/ads/placements?organicCount=20', 'GET', undefined, header)).body.items.length, 0);
    let version = 1;
    async function transition(action: string, h: Record<string, string>) { const r = await request(`/api/v1/admin/campaigns/${id}/transition`, 'POST', { action, version, reason: 'Test transition', confirmed: true }, h); if (r.status === 200)
        version++; return r; }
    assert.equal((await transition('activate', ch)).status, 409);
    assert.equal((await transition('submit', ch)).status, 200);
    assert.equal((await transition('approve', ch)).status, 409);
    assert.equal((await transition('approve', rh)).status, 200);
    assert.equal((await transition('activate', ch)).status, 200);
    const placements = await request('/api/v1/ads/placements?organicCount=20', 'GET', undefined, header);
    assert.equal(placements.body.items.length, 1, JSON.stringify(placements.body));
    const ad = placements.body.items[0];
    assert.equal((await request('/api/v1/ads/placements?organicCount=20', 'GET', undefined, header)).body.items.length, 0);
    assert.equal((await request(`/api/v1/ads/deliveries/${ad.deliveryId}`, 'GET', undefined, { Authorization: `Bearer ${stranger.token}` })).status, 404);
    await new Promise(r => setTimeout(r, 1100));
    const event = { deliveryId: ad.deliveryId, event: 'ad_impression', visibleMs: 1000 };
    await request('/api/v1/ads/events', 'POST', { events: [event, event] }, header);
    const n = await queryOne(`SELECT count(*) AS n FROM ad_events WHERE delivery_id=:'id' AND event_type='ad_impression'`, { id: ad.deliveryId });
    assert.equal(n?.n, '1');
    assert.equal((await request(`/api/v1/ads/deliveries/${ad.deliveryId}/report`, 'POST', { reason: 'scam' }, header)).status, 200);
    const report = await queryOne(`SELECT id FROM reports WHERE target_type='ad' AND target_id=:'id'`, { id: ad.creativeId });
    assert.ok(report);
    await request('/api/v1/ads/events', 'POST', { events: [{ deliveryId: ad.deliveryId, event: 'ad_hide', visibleMs: 0 }] }, header);
    assert.equal((await request(`/api/v1/ads/deliveries/${ad.deliveryId}`, 'GET', undefined, header)).status, 404);
    assert.equal((await transition('pause', ch)).status, 200);
    assert.equal((await request('/api/v1/ads/placements?organicCount=20', 'GET', undefined, { Authorization: `Bearer ${stranger.token}` })).body.items.length, 0);
    const edited = await request(`/api/v1/admin/campaigns/${id}/edit`, 'POST', { version, name: 'Reviewed again', caption: 'Updated caption', cta: 'Visit Website', destination: 'https://example.com/new', startAt: new Date(Date.now() - 60000).toISOString(), endAt: new Date(Date.now() + 3600000).toISOString(), confirmed: true }, rh);
    assert.equal(edited.status, 200, JSON.stringify(edited.body));
    version++;
    assert.equal((await transition('activate', ch)).status, 409);
    assert.equal((await transition('submit', ch)).status, 200);
    assert.equal((await transition('approve', rh)).status, 409, 'Last editor cannot approve their own changes');
    const independent = await account('ADMIN');
    const ih = await login(independent);
    assert.equal((await transition('approve', ih)).status, 200);
    assert.equal((await transition('activate', ch)).status, 200);
    const next = await request('/api/v1/ads/placements?organicCount=20', 'GET', undefined, { Authorization: `Bearer ${stranger.token}` });
    assert.equal(next.body.items.length, 1);
    await query(`UPDATE ad_campaigns SET start_at=now()-interval '2 days',end_at=now()-interval '1 day' WHERE id=:'id'`, { id });
    assert.equal((await request(`/api/v1/ads/deliveries/${next.body.items[0].deliveryId}`, 'GET', undefined, { Authorization: `Bearer ${stranger.token}` })).status, 404, 'Expiry invalidates a cached delivery');
    const removed = await request('/api/v1/admin/moderate', 'POST', { reportId: report!.id, version: 1, action: 'remove', reason: 'Ad violates policy', confirmed: true }, ih);
    assert.equal(removed.status, 200, JSON.stringify(removed.body));
    const state = await queryOne(`SELECT review_status FROM ad_creatives WHERE id=:'id'`, { id: ad.creativeId });
    assert.equal(state?.review_status, 'REMOVED');
});
it('ad operators can read required resources without gaining analytics or moderation access', async () => {
    const creator = await account('ADMIN', ['ads.create']);
    const h = await login(creator);
    assert.equal((await request('/api/v1/admin/campaigns', 'GET', undefined, h)).status, 200);
    assert.equal((await request('/api/v1/admin/advertisers', 'GET', undefined, h)).status, 200);
    assert.equal((await request('/api/v1/admin/campaigns/' + randomUUID() + '/analytics', 'GET', undefined, h)).status, 403);
    assert.equal((await request('/api/v1/admin/reports', 'GET', undefined, h)).status, 403);
    const viewer = await account('ADMIN', ['reports.read']);
    const vh = await login(viewer);
    assert.equal((await request('/api/v1/admin/campaigns', 'GET', undefined, vh)).status, 403);
});
