// The stack and the backend agree. The API, worker and migration containers get exactly the
// environment and secrets the stack defines: values AWS fills in at deploy time are replaced by
// realistic ones, and generated secrets are drawn under the template's own generator rules.
// Each container then runs the backend's real startup code (backend/dist). A credential left
// as its placeholder must stop startup, never run.
import { before, describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, randomBytes, randomInt } from "node:crypto";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { Template } from "aws-cdk-lib/assertions";
import { RDS_CA_BUNDLE, SECRET_PREFIX } from "../lib/katkee-stack";
import { cloudFrontKeys, container, everything, refTo, settings, synth, type Container } from "./helpers";

const backend = path.resolve(__dirname, "../../../backend");
const dist = path.join(backend, "dist");

/** What CloudFormation resolves at deploy time, by the variable that receives it. */
const DEPLOY_TIME: Record<string, string> = {
  PGHOST: "katkeeproduction-database.c9akciq32xyz.ap-south-1.rds.amazonaws.com",
  PGPORT: "5432",
  MEDIA_S3_BUCKET: "katkeeproduction-mediabucketbcbb02ba-1a2b3c4d5e6f",
  MEDIA_SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/123456789012/KatkeeProduction-MediaJobs0408E201-AbCdEfGh",
  MEDIA_CDN_DOMAIN: "d1a2b3c4d5e6f7.cloudfront.net",
  CLOUDFRONT_KEY_PAIR_ID: "K2JCJMDEHXQW5F",
};

const pem = (key: { export(o: { type: "pkcs8"; format: "pem" }): string | Buffer }) => key.export({ type: "pkcs8", format: "pem" }).toString();
/** What operators put in the provider secrets (infra/README.md), in the providers' real formats. */
const OPERATOR_VALUES: Record<string, string> = {
  CLOUDFRONT_PRIVATE_KEY: pem(cloudFrontKeys.privateKey),
  FCM_SERVICE_ACCOUNT_JSON: JSON.stringify({
    type: "service_account", project_id: "katkee-prod", private_key_id: randomBytes(20).toString("hex"),
    private_key: pem(generateKeyPairSync("rsa", { modulusLength: 2048 }).privateKey),
    client_email: "firebase-adminsdk@katkee-prod.iam.gserviceaccount.com", token_uri: "https://oauth2.googleapis.com/token",
  }),
  APNS_KEY_ID: "ABC123DEFG",
  APNS_TEAM_ID: "DEF456GHIJ",
  APNS_PRIVATE_KEY: pem(generateKeyPairSync("ec", { namedCurve: "prime256v1" }).privateKey),
  TWILIO_ACCOUNT_SID: `AC${randomBytes(16).toString("hex")}`,
  TWILIO_AUTH_TOKEN: randomBytes(16).toString("hex"),
  SAFE_BROWSING_API_KEY: `AIza${randomBytes(26).toString("base64url").slice(0, 35)}`,
};

/** Secrets Manager's password generator, following a GenerateSecretString block. */
function generated(spec: Record<string, any>): string {
  const PUNCTUATION = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
  const groups = [
    spec.ExcludeLowercase ? "" : "abcdefghijklmnopqrstuvwxyz",
    spec.ExcludeUppercase ? "" : "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    spec.ExcludeNumbers ? "" : "0123456789",
    spec.ExcludePunctuation ? "" : PUNCTUATION,
  ].map((g) => [...g].filter((c) => !String(spec.ExcludeCharacters ?? "").includes(c)).join("")).filter(Boolean);
  const all = groups.join("");
  const length = spec.PasswordLength ?? 32;
  // At least one of each included type, as the service does by default.
  const chars = groups.map((g) => g[randomInt(g.length)]!);
  while (chars.length < length) chars.push(all[randomInt(all.length)]!);
  const password = chars.sort(() => randomInt(3) - 1).join("");
  if (!spec.SecretStringTemplate) return password;
  return JSON.stringify({ ...JSON.parse(spec.SecretStringTemplate), [spec.GenerateStringKey]: password });
}

class Deployment {
  private readonly resources: Record<string, { Type: string; Properties: Record<string, any> }>;
  private readonly stored = new Map<string, string>();
  constructor(template: Template, private readonly placeholders: string[] = []) {
    this.resources = template.toJSON().Resources;
  }

  /** The value a secret holds after deploy: operator-filled, or generated by Secrets Manager. */
  private secretString(id: string): string {
    if (!this.stored.has(id)) {
      const props = this.resources[id]!.Properties;
      const name = String(props.Name).slice(SECRET_PREFIX.length);
      const filled = OPERATOR_VALUES[name] !== undefined && !this.placeholders.includes(name);
      this.stored.set(id, filled ? OPERATOR_VALUES[name]! : generated(props.GenerateSecretString));
    }
    return this.stored.get(id)!;
  }

  private secretValue(valueFrom: any): string {
    // A whole secret ({ Ref }) or one JSON key of it ({ Fn::Join: [<secret>, ":key::"] }).
    let id = valueFrom.Ref as string | undefined;
    let key: string | undefined;
    if (!id) {
      const [ref, suffix] = valueFrom["Fn::Join"][1] as [unknown, string];
      id = refTo(ref)!;
      key = /^:([^:]+)::$/.exec(suffix)![1];
    }
    if (this.resources[id]!.Type === "AWS::SecretsManager::SecretTargetAttachment") id = refTo(this.resources[id]!.Properties.SecretId)!;
    const value = this.secretString(id);
    return key ? (JSON.parse(value) as Record<string, string>)[key]! : value;
  }

  /** The process environment ECS gives this container. */
  environment(c: Container): Record<string, string> {
    const env: Record<string, string> = {};
    for (const { Name, Value } of c.Environment ?? []) {
      const value = typeof Value === "string" ? Value : DEPLOY_TIME[Name];
      assert.ok(value !== undefined, `${c.Name}: ${Name} is resolved at deploy time; add a realistic value to DEPLOY_TIME`);
      env[Name] = value;
    }
    for (const { Name, ValueFrom } of c.Secrets ?? []) env[Name] = this.secretValue(ValueFrom);
    return env;
  }
}

let consoleBuild = "";
before(() => {
  assert.ok(fs.existsSync(path.join(dist, "src/config/env.js")), "build the backend first (npm --prefix backend run build)");
  // The image builds the console into dist/admin (backend/Dockerfile); here, a fresh build stands in for it.
  consoleBuild = fs.mkdtempSync(path.join(os.tmpdir(), "katkee-console-"));
  const built = spawnSync(process.execPath, ["dist/scripts/build-admin.js", "../admin", consoleBuild], { cwd: backend, encoding: "utf8" });
  assert.equal(built.status, 0, built.stderr);
});

/** Runs startup code as the container would, from outside backend/ so no development .env is read. */
function start(env: Record<string, string>, script: string) {
  const local = {
    ...env,
    PATH: process.env.PATH ?? "",
    // The same CA bundle the image carries at RDS_CA_BUNDLE (see "the image provides").
    PGSSLROOTCERT: path.join(backend, "certs", path.basename(RDS_CA_BUNDLE)),
    ADMIN_STATIC_ROOT: consoleBuild,
  };
  return spawnSync(process.execPath, ["-e", script, dist], { cwd: os.tmpdir(), env: local, encoding: "utf8", timeout: 60_000 });
}

// The checks each process runs when it starts, then a report of what it configured.
const API = `const dist=process.argv[1];
require(dist+"/src/config/env.js");
require(dist+"/src/modules/auth/providers.js");
require(dist+"/src/app.js").buildApp();
console.log(JSON.stringify({push:[...require(dist+"/src/modules/push/dispatcher.js").providersFromConfig().keys()]}));
process.exit(0);`;
const WORKER = `const dist=process.argv[1];
const worker=require(dist+"/src/worker.js");
worker.createMediaWorker();
worker.createPushWorker();
console.log(JSON.stringify({push:[...require(dist+"/src/modules/push/dispatcher.js").providersFromConfig().keys()]}));
process.exit(0);`;
const MIGRATE = `const dist=process.argv[1];
const {database}=require(dist+"/src/config/database.js");
require(dist+"/scripts/runtime-role.js").validateRuntimeCredentials(process.env.DB_RUNTIME_USER,process.env.DB_RUNTIME_PASSWORD);
if(!database.ssl||database.ssl.rejectUnauthorized!==true||!database.ssl.ca)throw new Error("database TLS is not verified");
console.log(JSON.stringify({user:database.user,host:database.host}));
process.exit(0);`;

const report = (result: ReturnType<typeof start>) => JSON.parse(result.stdout.trim().split("\n").pop()!) as Record<string, unknown>;

describe("the backend starts with what the stack gives it", () => {
  const full = synth(everything()).template;
  const deployment = new Deployment(full);

  it("the API, with every provider and the Admin console on", () => {
    const result = start(deployment.environment(container(full, "api")), API);
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(report(result).push, ["fcm", "apns"]);
  });

  it("the worker", () => {
    const result = start(deployment.environment(container(full, "worker")), WORKER);
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(report(result).push, ["fcm", "apns"]);
  });

  it("the migration task: verified TLS to the database, a usable runtime role, no app secrets", () => {
    const env = deployment.environment(container(full, "migrate"));
    const result = start(env, MIGRATE);
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(report(result), { user: "katkee_owner", host: DEPLOY_TIME.PGHOST });
    assert.equal(env.DB_RUNTIME_USER, "katkee_app");
  });

  it("a minimal deploy: no providers", () => {
    const minimal = synth(settings()).template;
    const plain = new Deployment(minimal);
    const api = start(plain.environment(container(minimal, "api")), API);
    assert.equal(api.status, 0, api.stderr);
    assert.deepEqual(report(api).push, []);
    const worker = start(plain.environment(container(minimal, "worker")), WORKER);
    assert.equal(worker.status, 0, worker.stderr);
  });
});

describe("a credential left as its placeholder stops startup", () => {
  const full = synth(everything()).template;
  const cases: Array<[string, "api" | "worker", RegExp]> = [
    ["CLOUDFRONT_PRIVATE_KEY", "api", /CLOUDFRONT_PRIVATE_KEY must be the private key of the CloudFront key pair/],
    ["CLOUDFRONT_PRIVATE_KEY", "worker", /CLOUDFRONT_PRIVATE_KEY must be the private key of the CloudFront key pair/],
    ["TWILIO_ACCOUNT_SID", "api", /Phone authentication provider configuration is incomplete/],
    ["FCM_SERVICE_ACCOUNT_JSON", "worker", /FCM_SERVICE_ACCOUNT_JSON must be a Firebase service account key/],
    ["APNS_PRIVATE_KEY", "worker", /APNS_PRIVATE_KEY must be a private key/],
  ];
  for (const [name, which, error] of cases) {
    it(`${name} (${which})`, () => {
      const deployment = new Deployment(full, [name]);
      const result = start(deployment.environment(container(full, which)), which === "api" ? API : WORKER);
      assert.notEqual(result.status, 0, `${which} started with a placeholder ${name}`);
      assert.match(result.stderr, error);
    });
  }
});

describe("the image provides what the stack expects", () => {
  const dockerfile = fs.readFileSync(path.join(backend, "Dockerfile"), "utf8");

  it("the RDS CA bundle at its configured path", () => {
    assert.ok(RDS_CA_BUNDLE.startsWith("/app/certs/"));
    assert.match(dockerfile, /^WORKDIR \/app$/m);
    assert.match(dockerfile, /^COPY certs \.\/certs$/m);
    assert.ok(fs.existsSync(path.join(backend, "certs", path.basename(RDS_CA_BUNDLE))));
  });

  it("the commands the task definitions run, and a /tmp the read-only containers can write", () => {
    const { template } = synth(everything());
    assert.deepEqual(container(template, "migrate").Command, ["node", "dist/scripts/migrate.js"]);
    assert.ok(fs.existsSync(path.join(dist, "scripts/migrate.js")));
    // Two final stages (worker, runtime), each declaring /tmp a volume after switching to the app user.
    const stages = dockerfile.split(/^FROM /m).slice(1);
    for (const target of ["worker", "runtime"]) {
      const stage = stages.find((s) => s.split("\n")[0]!.endsWith(` AS ${target}`))!;
      assert.match(stage, /^USER node$/m, target);
      assert.match(stage, /^VOLUME \["\/tmp"\]$/m, target);
    }
    assert.match(dockerfile, /CMD \["node", "dist\/src\/worker\.js"\]/);
    assert.match(dockerfile, /CMD \["node", "dist\/src\/index\.js"\]/);
  });
});
